assets:
  css:
    - bundles/os2displaycampaign/assets/build/os2displaycampaign.min.css
  js_prod:
    - bundles/os2displaycampaign/assets/build/os2displaycampaign.min.js

apps:
  campaignApp:
    container: true
    files:
      - bundles/os2displaycampaign/apps/campaignApp/campaignApp.js
      - bundles/os2displaycampaign/apps/campaignApp/campaignModalBase.js
      - bundles/os2displaycampaign/apps/campaignApp/campaign-overview/campaignOverviewController.js
      - bundles/os2displaycampaign/apps/campaignApp/campaign-overview/campaignOverviewModalDelete.js
      - bundles/os2displaycampaign/apps/campaignApp/campaign/campaignController.js
      - bundles/os2displaycampaign/apps/campaignApp/campaign/campaignModalAddChannel.js
      - bundles/os2displaycampaign/apps/campaignApp/campaign/campaignModalAddScreen.js
      - bundles/os2displaycampaign/apps/campaignApp/campaign/campaignModalAddScreenGroup.js
      - bundles/os2displaycampaign/apps/campaignApp/directives/contenteditable.js
      - bundles/os2displaycampaign/apps/campaignApp/directives/screenList/campaignScreenList.js
      - bundles/os2displaycampaign/apps/campaignApp/directives/screenList/screenList.js
    dependencies:
      - ngRoute
      - ngAnimate
      - ngSanitize
      - busModule
      - mainModule
      - bw.paging
      - pascalprecht.translate
      - datetimePicker
      - angularModalService
      - styleguideComponentsModule
      - ikShared
