itk_campaign_homepage:
    path:     /campaign
    defaults: { _controller: Os2DisplayCampaignBundle:Default:index }

controllers:
  resource: '@Os2DisplayCampaignBundle/Controller'
  type: annotation
